# Generated by Django 2.2.24 on 2021-08-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0003_customer_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cus_name',
            new_name='pro_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='cus_qty',
            new_name='pro_qty',
        ),
    ]
