# Generated by Django 2.2.24 on 2021-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0005_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('language', models.TextField()),
            ],
        ),
    ]
