# Generated by Django 2.2.24 on 2021-08-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0006_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
