# Generated by Django 2.2.24 on 2021-08-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0009_auto_20210807_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aricle',
            name='reporter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Relations.Reporter'),
            preserve_default=False,
        ),
    ]
