# Generated by Django 2.2.24 on 2021-08-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0013_auto_20210807_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cus_id',
        ),
        migrations.AlterField(
            model_name='aricle',
            name='reporter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Relations.Creators'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
