# Generated by Django 2.2.24 on 2021-08-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0014_auto_20210807_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creators',
            name='created',
        ),
    ]
