# Generated by Django 2.2.24 on 2021-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relations', '0015_remove_creators_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='Relations.Publication')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
